name: model
description: A Flutter package for reusable widgets or utilities.
version: 1.0.0
publish_to: none  # Not publishing to pub.dev; used via GitHub

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  fl_chart: ^0.70.2
  flutter:
    sdk: flutter
  flutter_rating_bar: ^4.0.1
  flutter_slidable: ^4.0.0
  geolocator: ^13.0.4
  google_fonts: ^6.2.1
  google_maps_flutter: ^2.12.1
  google_places_flutter: ^2.1.0
  http: ^1.3.0
  intl: ^0.20.2
  lottie: ^3.3.1
  math_expressions: ^2.1.0
  shared_preferences: ^2.5.3
  timezone: ^0.10.0
  url_launcher: ^6.3.1
  video_player: ^2.9.5

dev_dependencies:
  flutter_test:
    sdk: flutter
